print('Hello visitor!')
print('Will u be able to conceal your thoughts or,')
print('Will I be able to prove my supernatural power!!')
print('Ready to challenge me!!')
print('')
name=input('Enter your name:')
print('All set to give it a go?')
x=input()
if x in ['YES', 'Yes' , 'yes']:
  print('')
  print('Dear,'+name )
  print('yeah!')
  print('You will be given a set of instructions, follow them honestly.')
  print('Do not tell anyone what you are thinking.')
  
  print('you donot have to utter a single word nor give me any input.')
  print('Yet, I will try my best to decode it!!')
  print('')
  print('let us start!!')
  
  y=input()
  if y in ['YES', 'Yes' , 'yes']:
    print('')
    print('Think of a "no. from 1-10"')
    print('Do not whisper it!')
    print('You might blame the air later!')
    print('')
    print('Have you choosen a number?')
    z=input()
    if z in ['YES', 'Yes' , 'yes']:
      print('')
      print('Multiply that number with 9')
      print('done?')
      q=input()
      if q in ['YES', 'Yes' , 'yes']:
        print('')
        print('"Add all the digits" of the number recieved in the previous step.')
        print('done?')
        w=input()
        if w in ['YES', 'Yes' , 'yes']:
          print('')
          print('"Subtract the number 4" from the number received in previous step.')
          print('Have you done all the steps till here correctly?')
          e=input()
          if e in ['YES', 'Yes' , 'yes']:
            print('')  
            print('Oh!! It is really tough to get you!!')
            print('But i will try my best.')
            print('')
            print('If you think i can still read your mind, type "okay" ')
            r=input()
            if r=="okay":
              print('')
              print('Think of the the letter from English alphabets that corresponds to the digit found in previous step.')
              print('for eg. 1=a,2=b.....26=z')
              print('')
              print('All good till here?')
              t=input()
              if t in ['YES', 'Yes' , 'yes']:
                print('')
                print('Think of an "animal" from that letter.')
                print('Keep repeating the name of the animal in your mind.')
                print('')
                print('Are you doing it?')
                y=input()
                if y in ['YES', 'Yes' , 'yes']:
                  print('')
                  print('OH!! let me challenge myself to the one more level.')
                  print('Come on!')
                  print('Think of the "colour" of the animal you thought of!')
                  print('')
                  print('done?')
                  u=input()
                  if u in ['YES', 'Yes' , 'yes']:
                    print('')
                    print('You are really hard to decode!')
                    print('Could you come a littel more close to the web cam!!')
                    print('Keep repeating the colour of the animal!!')
                    print('I can feel that you are thinking of "something gigantic"!!')
                    print('')
                    print('Are you ready for the surprise?')
                    i=input()
                    if i in ['YES', 'Yes' , 'yes']:
                      print('')
                      print('The colour was "GREY"!!')
                      print('')
                      print('AM I CORRECT? Are you surprised?')
                      o=input()
                      if o in ['YES', 'Yes' , 'yes']:
                        print('')
                        print('Told you! I am professional at telethesia!!')
                        print('I hope u enjoyed!')
                        print('Please, Do not play it again because I do not like to showing off my talents too much!')
                        print('')
                        print('Enjoyed?')
                        p=input()
                        if p in ['YES', 'Yes' , 'yes']:
                            
                            print('')
                            print('THANK YOU,' +name +'I ENJOYED YOUR COMPANY TOO!!')
                            print('Always remember:-')
                            print('Magic is real, it is just science, we donot understand yet!!')
                            print('GOOD LUCK!')
                            print('CHEERS!!')
                        elif p in ['NO', 'No' , 'no']:
                            print('')
                            print('OH!!WHAT DID YOU FIND MISSING?')
                            print('PLEASE WRITE IN THE COMMENTS!')
                            print('ANYWAYS THANKS!!')
                            print('CHEERS!')
                        
                        
                        
